<?php

$bx->box_begin();
$bx->box_title("Introduction");
$bx->box_body_begin();

echo "<B>DevCounter</B> queries open source developers for their knowledge and experiences as well as their cooperation\n";
echo "in open source projects. In addition, <B>DevCounter</B> allows precise searches for developers\n";
echo "with a specific know how.You can search additional developers for your project, or simply someone who assist you on\n";
echo "specific tasks, like: network programming, write documentation or perform a translation ...\n";
echo "<P>";
echo "Developer, which are looking for projects or want to help/assist, can subscribe at <B>DevCounter</B> with information about her knowledge and abilities.";

$bx->box_body_end();
$bx->box_end();
?>
