<?php

$bx->box_begin();
$bx->box_title("Introduction");
$bx->box_body_begin();

echo "<B>DevCounter</B> is an open, free and independent developer pool,\n";
echo "created to help developers to find other developers, help, testers and \n";
echo "new project members.\n";
echo "<P>";
echo "<B>DevCounter</B> queries open source developers for their knowledge\n";
echo "and experiences as well as their cooperation in open source projects.\n";
echo "In addition, <B>DevCounter</B> allows precise search for developers\n";
echo "with a specific know how. You can search additional developers for\n";
echo "your project, or simply someone who assist you on specific tasks,\n";
echo " like: network programming, write documentation or perform a\n";
echo "translation ...\n";
echo "<P>";
echo "Registered users are able to define a Developers Watch\n";
echo "which defines the abilities and experiences you are looking for.\n";
echo "If developers with these abilities and expriences becomes available,\n";
echo "the user will be informed via a message by email.\n";
echo "<P>";
echo "Registered users can also make requests if they looking for\n";
echo "help, project members or testers. The related project &amp; developer is directly linked\n";
echo "<P>";
echo "Developer, which are looking for projects or want to help/assist,\n";
echo "can subscribe at <B>DevCounter</B> with information about her\n";
echo "knowledge and abilities.";
echo "<P>";
echo "<B>Backlinking:</B><BR>\n";
echo "We asks everyone to put a link back to <B>DevCounter</B> on the home page or project page. \n";
echo "Text for short descriptions can be taken from this introduction.\n";

$bx->box_body_end();
$bx->box_end();
?>
