<?php

$bx->box_begin();
$bx->box_title("Einführung");
$bx->box_body_begin();

echo "<B>DevCounter</B> befragt Open-Source-Entwickler nach ihren Kentnissen und Erfahrungen sowie der Mitarbeit \n";
echo "an Open-Source-Projekten. Außerdem erlaubt <B>DevCounter</B> die zielgerichtete Suche nach Entwicklern \n";
echo "mit definierten Know-How. Man kann dort weitere Entwickler für die eigenen Projekte suchen oder einfach jemand, der bei\n";
echo "bestimmten Aufgaben kurz aushelfen kann, wie z.B. bei der Netzwerkprogrammierung, dem Schreiben von Dokumentation oder dem Erstellen von Übersetzungen.\n";
echo "<P>";
echo "Entwickler, die Projekte suchen und helfen wollen, können sich bei DevCounters unter Angaben ihrer Kenntnisse eintragen.";
$bx->box_body_end();
$bx->box_end();


?>
