<?php

$bx->box_begin();
$bx->box_title("Einführung");
$bx->box_body_begin();

echo "<B>DevCounter</B> ist ein offener, freier und unabh&auml;ngiger Entwicklerpool \n";
echo "der erstellt wurde um Entwicklern zu helfen andere Entwickler, Tester, Hilfe und \n";
echo "neue Projektmitglieder zu finden\n";
echo "<P>";
echo "<B>DevCounter</B> befragt Open-Source-Entwickler nach ihren Kentnissen\n";
echo "und Erfahrungen sowie der Mitarbeit an Open-Source-Projekten.\n";
echo "Außerdem erlaubt <B>DevCounter</B> die zielgerichtete Suche nach Entwicklern\n";
echo "mit definierten Know-How. Man kann dort weitere Entwickler für\n";
echo "die eigenen Projekte suchen oder einfach jemand, der bei\n";
echo "bestimmten Aufgaben kurz aushelfen kann, wie z.B. bei der\n";
echo "Netzwerkprogrammierung, dem Schreiben von Dokumentation oder dem\n";
echo "Erstellen von Übersetzungen.\n";
echo "<P>";
echo "Registrierte Benutzer können eine Entwicklerausschau definieren,\n";
echo "die Kentnisse und Erfahrungen von gesuchten Entwicklern beschreiben.\n";
echo "Sind Entwickler mit den gesuchten Kentnissen und Erfahrungen verfügbar,\n";
echo "dann wird der Benutzer durch eine Nachricht per E-Mail darüber informiert.\n";
echo "<P>";
echo "Registrierte Benutzer können zusätzlich Anfragen stellen, wenn sie Hilfe, \n";
echo "Projektmitglieder oder Tester suchen. Der entsprechende Entwicker und Projekt sind direkt verlinkt\n";
echo "<P>";
echo "Entwickler, die Projekte suchen und helfen wollen, können sich bei <B>DevCounters</B> ";
echo "unter Angabe ihrer Kenntnisse eintragen.";
echo "<P>";
echo "<B>Backlinking:</B><BR>\n";
echo "Wir bitten jeden einen Link zur&uuml;ck zu <B>DevCounter</B> in die Projekt- oder Homepage einzubauen. \n";
echo "Text f&uuml;r eine kurze Beschreibung kann von dieser Einf&uuml;hrung genommen werden.\n";

$bx->box_body_end();
$bx->box_end();
?>
