<?php

######################################################################
# SourceWell: Software Announcement & Retrieval System
# ================================================
#
# Copyright (c) 2001 by
#                Lutz Henckel (lutz.henckel@fokus.gmd.de) and
#                Gregorio Robles (grex@scouts-es.org)
#
# BerliOS SourceWell: http://sourcewell.berlios.de
# BerliOS - The OpenSource Mediator: http://www.berlios.de
#
# File with the main German translation
# translated by Lutz Henckel <lutz.henckel@fokus.gmd.de>
#
# This program is free software. You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 or later of the GPL.
######################################################################

switch($phrase) {

// Top strip
     case "Home": $tmp = "Heim"; break;
     case "About us": $tmp = "&Uuml;ber uns"; break;
     case "Partners": $tmp = "Partner"; break;
     case "Contact": $tmp = "Kontakt"; break;

     case "Logged in": $tmp = "Eingeloggt als"; break;
     case "Expires": $tmp = "Endet"; break;
     case "Not Logged in": $tmp = "Nicht eingeloggt"; break;

// Top title
     case "Open Source Software Announcement & Retrieval":  $tmp = "Open Source Software Ank&uuml;ndigung & Recherche"; break;

// Menue bar
     case "Developer": $tmp = "Entwickler"; break;
     case "Q&amp;A": $tmp = "F&amp;A"; break;
     case "Login": $tmp = "Einloggen"; break;
     case "Logout": $tmp = "Ausloggen"; break;
     case "New Developer": $tmp = "Neuer Entwickler"; break;
     case "Forgot Password": $tmp = "Passwort vergessen"; break;
     case "Change Developer": $tmp = "Entwickler &auml;ndern"; break;
     case "Developers": $tmp = "Entwickler"; break;
     case "Statistics": $tmp = "Statistiken"; break;
     case "Advanced Search": $tmp = "Erweiterte Suche";break;
     case "Backend": $tmp = "$phrase"; break;
     case "Modify ProgLanguages &amp; ProgTools": $tmp = "ProgSprachen und ProgTools verwalten";break;

//Frontpage
     case "Newest Developers": $tmp = "Neueste Entwickler"; break;


//Permissions
     case "allow to show realname": $tmp = "tats&auml;chlicher Name darf angezeigt werden"; break;
     case "allow to show E-Mail": $tmp = "E-Mail darf angezeigt werden"; break;
     case "allow to be searched": $tmp = "Darf gefunden werden"; break;
     case "allow to be contacted by DevCounter": $tmp = "Darf von DevCounter kontaktiert werden"; break;
     case "Register as a new Developer": $tmp = "Als neuer Entwicker anmelden"; break;
     
//Statiscs and Profile
     case "Total number of developers": $tmp = "Gesamtazahl der Entwickler";break;
     case "no entry": $tmp = "Kein Eintrag";break;
     case "No Entry": $tmp = "Kein Eintrag";break;
     case "Gender": $tmp = "Geschlecht";break;
     case "Male": $tmp = "Männlich";break;
     case "Female": $tmp = "Weiblich";break;

     case "Qualification": $tmp = "Abschluß"; break;
     case "Elementary School": $tmp = "Grundschule"; break;
     case "High School": $tmp = "Oberschule"; break;
     case "A-Level": $tmp = "Abitur"; break;
     case "Apprenticeship": $tmp = "Lehre"; break;
     case "College Graduate": $tmp = "Hochschulabschluß"; break;
     case "University Graduate": $tmp = "Universitätsabschluß"; break;
     case "PhD": $tmp = "Doktor (akad.)"; break;

     case "Profession": $tmp = "Beruf"; break;
     case "Programmer": $tmp = "Programmierer"; break;
     case "Engineer": $tmp = "Ingeneur"; break;
     case "University professor/assistant": $tmp = "Universitätsprofessor/-assistent"; break;
     case "Consultant": $tmp = "Berater"; break;
     
     case "IT or not IT": $tmp = "IT oder nicht IT"; break;
     case "Not IT": $tmp = "Nicht IT"; break;

     case "Enter your Profile": $tmp = "Profildaten eingeben"; break;
     case "Update your Profile": $tmp = "Profildaten ändern"; break;

     case "Nationality": $tmp = "Herkunftsland"; break;
     case "Country you actually live in": $tmp = "Land, in dem Du zur Zeit lebst"; break;
     case "Year of Birth": $tmp = "Geburtsjahr"; break;
     case "Mother tongue": $tmp = "Muttersprache"; break;
     case "Other languages": $tmp = "weitere Sprachen"; break;

     
     case "Project": $tmp = "Projekt"; break;
     case "Number of Free Software/Open Source Projects you are involved in": $tmp = "Anzahl der Free Software/Open Source Projekte in die eingebunden bist"; break;
     case "Which of these programming expirience do you have?": $tmp = "In welchen Bereichen hast Du Erfahrung?"; break;
     case "Which of these languages/tools are you experienced with?": $tmp = "In welchen dieser Sprachen/Tools hast Du Erfahrung?"; break;
     case "Professional Data": $tmp = "Ausbildung & Beruf"; break;
     case "Personal Data": $tmp = "Persönliche Daten"; break;
     case "Computer experience": $tmp = "Computer Erfahrung"; break;
     case "Submit": $tmp = "Abschicken"; break; 
     case "Submit Your Form": $tmp = "Formular abschicken"; break; 
     case "Add Project": $tmp = "Projekt hinzufügen"; break; 
     case "Please enter Project Data": $tmp = "Bitte Projektdaten eingeben"; break; 
     case "Projectname": $tmp = "Projektname"; break; 
     case "ProjectURL": $tmp = "ProjektURL"; break; 

     
     case "No Experience": $tmp = "Keine Erfahrung"; break;
     case "Novice": $tmp = "Einsteiger"; break;
     case "Beginner": $tmp = "Anfänger"; break;
     case "Advanced": $tmp = "Fortgeschrittner"; break;
     case "Expert": $tmp = "Experte"; break;

     case "Projects": $tmp = "Projekte"; break;
     case "Manage your Project List": $tmp = "Projektliste verwalten"; break;

     case "Search": $tmp = "Suche"; break;
     case "Language": $tmp = "Sprache"; break;
     case "Go": $tmp = "Los"; break;

// Languages
	 case "English": $tmp = "Englisch"; break;
	 case "German": $tmp = "Deutsch"; break;
	 case "Spanish": $tmp = "Spanisch"; break;
	 case "French": $tmp = "Französisch"; break;

// sorted by
	 case "sorted by": $tmp = "sortiert nach"; break;
	 case "Date": $tmp = "Datum"; break;
	 case "Importance": $tmp = "Bedeutung"; break;
	 case "Urgency": $tmp = "Dringlichkeit"; break;
	 case "Name": $tmp = "Name"; break;

// FAQ
     case "Frequently Asked Questions": $tmp = "Oft gestellte Fragen"; break;
     case "Question": $tmp = "Frage"; break;
     case "Answer": $tmp = "Antwort"; break;

//Search
     case "DevCounter Search by Category": $tmp = "DevCounter Kategoriesuche"; break;
     case "Countries": $tmp = "L&auml;nder"; break;
     case "Spoken Languages": $tmp = "Gesprochene Sprachen"; break;
     case "Programming &amp; Computer Abilities": $tmp = "Programmier- &amp; Computerf&auml;higkeiten"; break;
     case "All in one": $tmp = "Alles auf einmal"; break;
     case "Search for Languages spoken": $tmp = "Suche nach gesprochen Sprachen"; break;
     case "Please select desired Language": $tmp = "Bitte gew&uuml;nschte Sprache ausw&auml;hlen"; break;
     case "Search for Projects": $tmp = "Suche nach Projekten"; break;
     case "Enter Name of <B>one</B> Project": $tmp = "Gib den Namen <B>eines</B> Projektes ein"; break;
     case "Results": $tmp = "Ergebnisse"; break;
     case "No Results": $tmp = "keine Ergebnisse"; break;
     case "Search Results": $tmp = "Suchergebisse"; break;
     case "Search for Countries": $tmp = "Suche nach L&auml;ndern"; break;
     case "Please select desired Country": $tmp = "Bitte das gew&uuml;nschte Land ausw&auml;hlen"; break;
     case "Search for All in one": $tmp = "Nach allem auf einmal suchen"; break;


// Apps update
     case "Comment": $tmp = "Kommentar"; break;
     case "Review": $tmp = "Überprüfen"; break;
     case "Update": $tmp = "Aktualisieren"; break;
     case "Delete": $tmp = "Löschen"; break;
     case "Undelete": $tmp = "Wiederherstellen"; break;


// Apps by identifier
     case "Application": $tmp = "Anwendung"; break;
     case "Others by Author": $tmp = "Anderes vom Autor"; break;
     case "has not yet been reviewed by a $GLOBALS[sys_name] Editor.<br> Please, be patient. It will be surely done in the next time.": $tmp = "wurde noch nicht von einem $GLOBALS[sys_name] Editor überprüft.<br> Bitte haben Sie noch etwas Geduld. In n&auml;chster Zeit wird dies bestimmt geschehen."; break;
     case "is modified": $tmp = "ist modifiziert"; break;
     case "is deleted": $tmp = "ist gelöscht"; break;

// User registration
     case "Register as a new User": $tmp = "Registrierung als neuer Benutzer"; break;
     case "Username": $tmp = "Benutzername"; break;
     case "Password": $tmp = "Passwort"; break;
     case "Confirm Password": $tmp = "Passwort bestätigen"; break;
     case "Realname": $tmp = "Name"; break;
     case "Register": $tmp = "Registrieren"; break;
     case "User Registration": $tmp = "Benutzerregistrierung"; break;
     case "Congratulations": $tmp = "Gratulation"; break;
     case "You have registered on $GLOBALS[sys_name]": $tmp = "Sie haben sich bei $GLOBALS[sys_name] registriert"; break;
     case "Your new username is": $tmp = "Ihr neuer Benutzername ist"; break;
     case "You are now being sent a confirmation email to verify your email address": $tmp = "Es wurde eine Bestätigung per E-Mail an Sie gesendet, um Ihre E-Mail-Adresse zu überprüfen"; break;
     case "Visiting the link sent to you in this email will activate your account": $tmp = "Wenn Sie die in dieser E-Mail gesendete Seite besuchen wird Ihre Benutzerkennung freigeschaltet"; break;
     case "Thank you for registering on the $GLOBALS[sys_name] Site. In order": $tmp = "Danke für Ihre Registrierung bei $GLOBALS[sys_name]. Um Ihre"; break;
     case "to complete your registration, visit the following URL": $tmp = "Registrierung abzuschließen, besuchen Sie die folgende URL"; break;
     case "Enjoy the site": $tmp = "Wir hoffen, dass Ihnen $GLOBALS[sys_name] gefällt"; break;
     case " -- the $GLOBALS[sys_name] crew": $tmp = " -- die $GLOBALS[sys_name] Crew"; break;
     case "Verification of Registration": $tmp = "Verifikation der Registrierung"; break;
     case "Your account is now activated. Please login": $tmp = "Ihre Benutzerkennung ist jetzt freigeschaltet. Bitte loggen Sie sich ein"; break;

// Contact Developer
     case "Send": $tmp = "Senden"; break;
     case "contact developer": $tmp = "an Entwickler schreiben"; break;
     case "Contact Developer": $tmp = "an Entwickler schreiben"; break;     
     case "Subject:": $tmp = "Betreff:"; break;
     case "Your EMail Address:": $tmp = "Deine EMail Adresse"; break;
     case "Content:": $tmp = "Inhalt:"; break;

// Forget password / Remind me
     case "Register as a new User": $tmp = "Registrierung als neuer Benutzer"; break;
     case "Remind me": $tmp = "Erinnern"; break;
     case "Your Username and Password for $GLOBALS[sys_name] is": $tmp = "Ihr Benutzername und Passwort für $GLOBALS[sys_name] ist"; break;
     case "Please keep this e-mail for further reference": $tmp = "Bitte bewahren Sie diese E-Mail zur späteren Referenzierung auf"; break;
     case "You will get your Password by e-mail in a couple of minutes": $tmp = "Sie erhalten Ihr Passwort per E-Mail in wenigen Minuten"; break;

// Change User Parameters
     case "Change Developer Parameters": $tmp = "Änderung der Entwicklerdaten"; break;
     case "Remind me": $tmp = "Erinnerung"; break;
     case "Modification": $tmp = "Modifiziert"; break;
     case "Creation": $tmp = "Erzeugt"; break;
     case "Permission": $tmp = "Rechte"; break;
     case "Change": $tmp = "Ändern"; break;
     case "Password and/or E-Mail Address of": $tmp = "Passwort und/oder E-Mail-Adresse von"; break;
     case "is changed": $tmp = "wurden geändert"; break;

// Login
     case "$GLOBALS[sys_name] Login": $tmp = "Bei $GLOBALS[sys_name] Einloggen"; break;
     case "Welcome to $GLOBALS[sys_name]": $tmp = "Willkommen bei $GLOBALS[sys_name]"; break;
     case "You are logged in as": $tmp = "Sie sind eingeloggt als"; break;
     case "with": $tmp = "mit"; break;
     case "permission": $tmp = "Rechten"; break;
     case "Your authentication is valid until": $tmp = "Ihre Authentifizierung ist gültig bis"; break;

// Logout
     case "You have been logged in as": $tmp = "Sie waren eingeloggt als"; break;
     case "Your authentication was valid until": $tmp = "Ihre Authentifizierung war gültig bis"; break;
     case "This is all over now. You have been logged out": $tmp = "Dies ist nun vorbei. Sie haben sich ausgeloggt"; break;

// User admin
     case "Action": $tmp = "Aktion"; break;
     case "Delete": $tmp = "Löschen"; break;
     case "Create User": $tmp = "Benutzer Erzeugen"; break;
     case "User Creation": $tmp = "Benutzer einrichten"; break;
     case "created": $tmp = "eingerichtet"; break;
     case "User Change": $tmp = "Benutzer Ändern"; break;
     case "User Deletion": $tmp = "Benutzer Löschen"; break;
     case "is deleted": $tmp = "wurden gelöscht"; break;

// Announcements
    case "by": $tmp = "von"; break;
    case "on": $tmp = "am"; break;
	case "hits": $tmp = "Zugriffe"; break;

// Statistics
	 case "$GLOBALS[sys_name] Statistics": $tmp = "$GLOBALS[sys_name] Statistiken"; break;
	 case "General $GLOBALS[sys_name] Statistics": $tmp = "Allgemeine $GLOBALS[sys_name] Statistiken"; break;

// General Statistics
	 case "Number of Applications in $GLOBALS[sys_name]": $tmp = "Anzahl der Anwendungen in $GLOBALS[sys_name]"; break;
	 case "Total Number of Insertions and Modifications": $tmp = "Gesamtzahl der Eintragungen und Modifikationen"; break;
	 case "Number of Insertions and Modifications during the last week": $tmp = "Anzahl der Eintragungen und Modifikationen in der letzen Woche"; break;
	 case "Number of pending Applications": $tmp = "Anzahl der zu prüfenden Anwendungen"; break;
	 case "Number of $GLOBALS[sys_name] authorised Users": $tmp = "Anzahl der bei $GLOBALS[sys_name] registrierten Benutzer"; break;
	 case "Number of Comments on Applications": $tmp = "Anzahl der Kommentare zu Anwendungen"; break;
	 case "Number of Licenses listed in $GLOBALS[sys_name]": $tmp = "Anzahl der Lizenzen in $GLOBALS[sys_name]"; break;
	 case "Number of $GLOBALS[sys_name] Sections": $tmp = "Anzahl der Sektionen in $GLOBALS[sys_name]"; break;
	 case "Number of $GLOBALS[sys_name] Categories": $tmp = "Anzahl der Kategorien in $GLOBALS[sys_name]"; break;
	 case "Number of Hits on Applications": $tmp = "Anzahl der Zugriffe auf Anwendungen"; break;
	 case "Number of redirected Homepages": $tmp = "Anzahl der Zugriffe auf Homepages"; break;
	 case "Number of Downloads": $tmp = "Anzahl der Zugriffe auf Downloads"; break;
	 case "Number of redirected Changelogs": $tmp = "Anzahl der Zugriffe auf Changlogs"; break;
	 case "Number of redirected CVSs": $tmp = "Anzahl der Zugriffe auf CVS-Verzeichnisse"; break;
	 case "Number of redirected Screenshots": $tmp = "Anzahl der Zugriffe auf Screenshots"; break;
	 case "Number of redirected Mailing Lists Archives": $tmp = "Anzahl der Zugriffe auf Mailing-Lists-Archive"; break;
	 case "$GLOBALS[sys_name] Version": $tmp = "$GLOBALS[sys_name] Version"; break;

	 case "High Urgency": $tmp = "Hohe Bedeutung"; break;
	 case "Medium Urgency": $tmp = "Mittlere Bedeutung"; break;
	 case "Low Urgency": $tmp = "Geringe Bedeutung"; break;
	 case "Stable Version": $tmp = "Stabile Version"; break;
	 case "Development Version": $tmp = "Entwicklungsversion"; break;
	 case "Version Number": $tmp = "Versionsnummer"; break;
	 case "Tarballs": $tmp = "$phrase"; break;
	 case "Red Hat Packages": $tmp = "Red Hat Pakete"; break;
	 case "Debian Packages": $tmp = "Debian Pakete"; break;
	 case "Slackware Packages": $tmp = "Slackware Pakete"; break;
	 case "Applications listed by their Importance": $tmp = "Anwendungen geordnet nach ihrer Bedeutung"; break;
	 case "Applications listed by Number of Tarball-Downloads": $tmp = "Anwendungen geordnet nach Anzahl der Tarball-Downloads"; break;
	 case "Applications listed by Number of Hits": $tmp = "Anwendungen geordnet nach Anzahl der Zugriffe"; break;
	 case "Applications listed by Homepage Visits": $tmp = "Anwendungen geordnet nach Anzahl der Homepage-Besuche"; break;
	 case "Top downloaded Red Hat Packages": $tmp = "Top der heruntergeladenen RPM-Pakete"; break;
	 case "Top downloaded Debian Packages": $tmp = "Top der heruntergeladenen Debian-Pakete"; break;
	 case "Top downloaded Slackware Packages": $tmp = "Top der heruntergeladenen Slackware-Pakete"; break;
	 case "Application Importance listed by Sections": $tmp = "Anwendungsbedeutung geordnet nach Sektionen"; break;
	 case "Applications listed by Sections": $tmp = "Anwendungen geordnet nach Sektionen"; break;
	 case "Applications listed by Categories": $tmp = "Anwendungen geordnet nach Kategrien"; break;
	 case "Applications listed by Licenses": $tmp = "Anwendungen geordnet nach Lizenzen"; break;
	 case "Availability of downloadable Packet Formats": $tmp = "Verfügbarkeit von herunterladbaren Paketformaten"; break;
	 case "Downloads listed by Packet Formats": $tmp = "Downloads geordnet nach Paketformaten"; break;
	 case "Applications listed by Urgency": $tmp = "Anwendungen geordnet nach Dringlichkeit"; break;
	 case "Downloads listed by Urgency": $tmp = "Downloads geordnet nach Dringlichkeit"; break;
	 case "Applications listed by Version Numbers": $tmp = "Anwendungen geordnet nach Versionsnummern"; break;
	 case "Applications listed by Licenses": $tmp = "Anwendungen geordnet nach Lizenzen"; break;
	 case "Applications listed by Version Type": $tmp = "Anwendungen geordnet nach Versionstypen"; break;
	 case "Downloads listed by Version Type": $tmp = "Downloads geordnet nach Versionstypen"; break;
	 case "Application Importance listed by Licenses": $tmp = "Anwendungsbedeutung geordnet nach Lizenzen"; break;
	 case "Application Importance listed by Developer's Email Domains": $tmp = "Anwendungsbedeutung geordnet nach E-Mail-Domainen der Entwickler"; break;
	 case "Applications listed by Developer's Email Domain": $tmp = "Anwendungen geordnet nach E-Mail-Domainen der Entwickler"; break;
	 case "Applications listed by Sections and Developer's Email Domain": $tmp = "Anwendungen geordnet nach Sektionen und E-Mail-Domainen der Entwickler"; break;
	 case "Applications listed by Licenses and Developer's Email Domain": $tmp = "Anwendungen geordnet nach Lizenzen und E-Mail-Domainen der Entwickler"; break;

// Errors
     case "Access denied": $tmp = "Zugriff verweigert"; break;
     case "Error": $tmp = "Fehler"; break;
     case "does not exist": $tmp = "existiert nicht"; break;
     case "Change User Parameters failed": $tmp = "Änderung der Benutzerdaten ist fehlgeschlagen"; break;
     case "No Application ID specified": $tmp = "Keine Anwendungs-ID angegeben"; break;
     case "No Application Name specified": $tmp = "Kein Anwendungsname angegeben"; break;
     case "Please select": $tmp = "Bitte wählen Sie"; break;
     case "Parameter missing": $tmp = "Parameter fehlt"; break;
     case "and": $tmp = "und"; break;
     case "User": $tmp = "Benutzer"; break;
     case "already exists": $tmp = "existiert bereits"; break;
     case "Please select a different Username": $tmp = "Bitte wählen Sie einen anderen Benutzernamen"; break;
     case "Please enter": $tmp = "Bitte angeben:"; break;
     case "Either your Username or E-Mail Address is unknown": $tmp = "Entweder Ihr Benutzername oder E-Mail-Adresse ist unbekannt"; break;
     case "Please try again": $tmp = "Bitte versuchen Sie es nochmal"; break;
     case "If you are not yet a registered User, please select": $tmp = "Wenn Sie noch kein registrierter Benutzer sind, wählen Sie bitte"; break;
     case "Verification of Registration failed": $tmp = "Verifikation der Registrierung ist fehlgeschlagen"; break;
     case "User Change failed": $tmp = "Benutzer ändern ist fehlgeschlagen"; break;
     case "Registration of new User failed": $tmp = "Registrierung des neuen Benutzers ist fehlgeschlagen"; break;
     case "Database Access failed": $tmp = "Datenbankzugriff ist fehlgeschlagen"; break;
     case "User Deletion failed": $tmp = "Benutzer Löschen ist fehlgeschlagen"; break;
     case "No more Apps for this day": $tmp = "Keine weiteren Anwendungen für diesen Tag"; break;
     case "Either your Username or Password are invalid": $tmp = "Entweder Ihr Benutzername oder Passwort ist falsch"; break;
     case "The passwords are not identical": $tmp = "Die Passworte sind nicht identisch"; break;
     case "Please try again": $tmp = "Bitte versuchen Sie es nochmal"; break;
     case "License description is not available": $tmp = "Lizenzbeschreibung ist nicht verfügbar"; break;
     case "No Frequently Asked Questions exist": $tmp = "Es existieren keine oft gestellten Fragen"; break;

// adm_langs_tools.php3
    case "Success": $tmp = "Erfolg"; break;
    case "ProgLanguage": $tmp = "Programmiersprache"; break;
    case "ColumnName": $tmp = "Spaltenname"; break;
    case "Programming Abilities" : $tmp = "Programmierfertigkeiten"; break;
    case "ProgAbilityName" : $tmp = "ProgFertigkeitenName"; break;
    case "Programming Languages": $tmp = "Programmiersprachen"; break;
    case "ProgLanguageName": $tmp = "ProgSprachenName"; break;
    case "ProgLanguage updated": $tmp = "ProgSprache ge&auml;ndert"; break;
    case "ProgLanguage added": $tmp = "ProgSprache hinzugef&uuml;gt"; break;
    case "ProgLanguage removed": $tmp = "ProgSprache entfernt"; break;
    case "Ability updated": $tmp = "F&auml;higkeit ge&auml;ndert"; break;
    case "Ability added": $tmp = "F&auml;higkeit hinzugef&uuml;gt"; break;
    case "Add Ability": $tmp = "F&auml;higkeit hinzuf&uuml;gen"; break;
    case "Add ProgLanguage": $tmp = "ProgSprache hinzuf&uuml;gen"; break;
    case "Ability removed": $tmp = "F&auml;higkeit entfernt"; break;

// stats.php3
    case "Number of Insertions and Modifications in the last day": $tmp = "Anzahl der Eintragungen und Modifikationen während des letzten Tages"; break;
    case "Number of today's visitors": $tmp = "Anzahl der heutigen Besucher"; break;
    case "Today": $tmp = "Heute"; break;
    case "Version Number":  $tmp = "Versionsnummer"; break;

// admuser.php3
    case "User Administration": $tmp = "Benutzeradministration"; break;
    case "There can only be one anonymous user in the system": $tmp = "Es darf nur ein anonymer Benutzer existieren"; break;
    case "The anonymous permission is incompatible with another type of permission": $tmp = "Das anonyme Recht ist inkompatibel zu anderen Rechten"; break;


// showprofile.php3

    case "actually live in": $tmp = "lebt momentan in"; break;
    case "Languages spoken": $tmp = "gesprochene Sprachen"; break;
    case "Number of Free Software/Open Source Projects": $tmp = "Anzahl der Free Software/Open Source Projekte"; break;
    
// admfaq.php3 and insfaq.php3

    case "Enter a New Frequently Asked Question": $tmp = "Erstellen einer neuen häufig gestellten Frage"; break;
    case "Frequently Asked Questions Administration": $tmp = "Administration der häufig gestellten Fragen"; break;
    case "Delete this faq? (please, think there's no way for undoing comment deletion)": $tmp = "Diese Frage löschen? (Bitte bedenken Sie, dass es keine Möglichkeit gibt, dies wieder rückgängig zu machen)"; break;
    case "Create": $tmp = "Erstelle"; break;
    case "FAQ Deleted": $tmp = "Frage gelöscht"; break;
    case "FAQ Administration": $tmp = "Administration der häufig gestellten Fragen"; break;
    case "The following FAQ has been modified": $tmp = "Die folgende Frage wurde geändert"; break;
    case "The following FAQ has been inserted in this language": $tmp = "Die folgende Frage wurde erstellt in der Sprache"; break;

// admdate.php3
    case "Modification date": $tmp = "Änderungsdatum"; break;
    case "History date": $tmp = "Datum der Historie"; break;

// footer.inc
    case "System Credits": $tmp = "Systembeschreibung"; break;

// login.php3
    case "Anonymous login": $tmp = "Anonymes Login"; break;
    case "If you are not registered and/or you do not want to, you can login as an anonymous user by entering": $tmp = "Wenn Sie nicht registriert sind und/oder Sie möchten dies auch nicht, dann authentifizieren Sie sich als anonymer Benutzer durch Eingabe von"; break;
    case "as user name and": $tmp = "als Benutzername und"; break;
    case "as password.": $tmp = "als Passwort"; break;

// configure.php3

// If no translation available, keep the original phrase
     default: $tmp = "$phrase"; break;
}
?>
