<?php

######################################################################
# Devcounter: Open Source Developer Counter
# ================================================
#
# Copyright (c) 2001-2002 by
#       Lutz Henckel (lutz.henckel@fokus.fhg.de)
#       Gregorio Robles (grex@scouts-es.org)
#       Stefan Heinze (heinze@fokus.fhg.de)
#
# BerliOS DevCounter: http://devcounter.berlios.de
# BerliOS - The OpenSource Mediator: http://www.berlios.de
#
# File with the main German translation
# translated by Lutz Henckel <lutz.henckel@fokus.fhg.de>
#
# This program is free software. You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 or later of the GPL.
######################################################################

switch($phrase) {

// Top strip
     case "Home": $tmp = "Heim"; break;
     case "About us": $tmp = "&Uuml;ber uns"; break;
     case "Partners": $tmp = "Partner"; break;
     case "Contact": $tmp = "Kontakt"; break;

     case "Logged in": $tmp = "Eingeloggt als"; break;
     case "Expires": $tmp = "Endet"; break;
     case "Not Logged in": $tmp = "Nicht eingeloggt"; break;

// Top title
     case "Open Source Software Announcement & Retrieval":  $tmp = "Open Source Software Ank&uuml;ndigung & Recherche"; break;

// Menue bar
     case "Developer": $tmp = "Entwickler"; break;
     case "Q&amp;A": $tmp = "F&amp;A"; break;
     case "Login": $tmp = "Einloggen"; break;
     case "Logout": $tmp = "Ausloggen"; break;
     case "New Developer": $tmp = "Neuer Entwickler"; break;
     case "Forgot Password": $tmp = "Passwort vergessen"; break;
     case "Change Developer": $tmp = "Entwickler &auml;ndern"; break;
     case "Developers Watch": $tmp = "Entwicklerausschau"; break;
     case "Developers": $tmp = "Entwickler"; break;
     case "Statistics": $tmp = "Statistiken"; break;
     case "Advanced Search": $tmp = "Erweiterte Suche";break;
     case "Backend": $tmp = "$phrase"; break;
     case "Modify ProgLanguages &amp; ProgTools": $tmp = "ProgSprachen und ProgTools verwalten";break;
     case "Daily Newsletter": $tmp = "Tägl. Newsletter"; break;
     case "Weekly Newsletter": $tmp = "Wöchentl. Newsletter"; break;

//Frontpage
     case "Newest Developers": $tmp = "Neueste Entwickler"; break;
     case "Please enter your Profile": $tmp = "Bitte geben Sie Ihre Profildaten ein"; break;

//Permissions
     case "allow to show realname": $tmp = "tats&auml;chlicher Name darf angezeigt werden"; break;
     case "allow to show E-Mail": $tmp = "E-Mail darf angezeigt werden"; break;
     case "allow to be searched": $tmp = "Darf gefunden werden"; break;
     case "allow to be contacted by DevCounter": $tmp = "Darf von DevCounter kontaktiert werden"; break;
     case "Register as a new Developer": $tmp = "Als neuer Entwicker anmelden"; break;
     
//Statiscs and Profile
     case "Total number of developers": $tmp = "Gesamtazahl der Entwickler";break;
     case "no entry": $tmp = "kein Eintrag";break;
     case "No Entry": $tmp = "Kein Eintrag";break;
     case "Gender": $tmp = "Geschlecht";break;
     case "Male": $tmp = "Männlich";break;
     case "Female": $tmp = "Weiblich";break;

     case "Qualification": $tmp = "Abschluß"; break;
     case "Elementary School": $tmp = "Grundschule"; break;
     case "High School": $tmp = "Oberschule"; break;
     case "A-Level": $tmp = "Abitur"; break;
     case "Apprenticeship": $tmp = "Lehre"; break;
     case "College Graduate": $tmp = "Hochschulabschluß"; break;
     case "University Graduate": $tmp = "Universitätsabschluß"; break;
     case "PhD": $tmp = "Doktor (akad.)"; break;

     case "Profession": $tmp = "Beruf"; break;
     case "Programmer": $tmp = "Programmierer"; break;
     case "Engineer": $tmp = "Ingenieur"; break;
     case "Student (other)": $tmp = "Student (andere)"; break;
     case "Software Engineer": $tmp = "Software Ingenieur"; break;
     case "University professor/assistant": $tmp = "Universitätsprofessor/-assistent"; break;
     case "University professor/assistant (IT)": $tmp = "Universitätsprofessor/-assistent (IT)"; break;
     case "University professor/assistant (other)": $tmp = "Universitätsprofessor/-assistent (andere)"; break;
     case "Consultant": $tmp = "Berater"; break;
     case "Consultant (IT)": $tmp = "Berater (IT)"; break;
     case "Consultant (other)": $tmp = "Berater (andere)"; break;
     case "Executive": $tmp = "Selbstst&auml;ndiger"; break;
     case "Executive (IT)": $tmp = "Selbstst&auml;ndiger (IT)"; break;
     case "Executive (other)": $tmp = "Selbstst&auml;ndiger (andere)"; break;
     case "Nothing to do with the software industry": $tmp = "Nichts mit der Software Industrie zu tun"; break;
     
     case "IT or not IT": $tmp = "IT oder nicht IT"; break;
     case "Not IT": $tmp = "Nicht IT"; break;

     case "Enter your Profile": $tmp = "Profildaten eingeben"; break;
     case "Update your Profile": $tmp = "Profildaten ändern"; break;

     case "Nationality": $tmp = "Herkunftsland"; break;
     case "Country you currently live in": $tmp = "Land, in dem Du zur Zeit lebst"; break;
     case "Year of Birth": $tmp = "Geburtsjahr"; break;
     case "Mother tongue": $tmp = "Muttersprache"; break;
     case "Other languages": $tmp = "weitere Sprachen"; break;
     
     case "Project": $tmp = "Projekt"; break;
     case "Number of Free Software/Open Source Projects you are involved in": $tmp = "Anzahl der Free Software/Open Source Projekte in die eingebunden bist"; break;
     case "Which of these programming experience do you have?": $tmp = "In welchen Bereichen hast Du Erfahrung?"; break;
     case "Which of these languages/tools are you experienced with?": $tmp = "In welchen dieser Sprachen/Tools hast Du Erfahrung?"; break;
     case "Professional Data": $tmp = "Ausbildung & Beruf"; break;
     case "Personal Data": $tmp = "Persönliche Daten"; break;
     case "Computer Experience": $tmp = "Computer-Erfahrung"; break;
     case "Submit": $tmp = "Abschicken"; break; 
     case "Submit Your Form": $tmp = "Formular abschicken"; break; 
     case "Add Project": $tmp = "Projekt hinzufügen"; break; 
     case "Please enter your Project Data": $tmp = "Bitte Projektdaten eingeben"; break; 
     case "Projectname": $tmp = "Projektname"; break; 
     case "ProjectURL": $tmp = "ProjektURL"; break;
 
     case "No Experience": $tmp = "Keine Erfahrung"; break;
     case "Novice": $tmp = "Einsteiger"; break;
     case "Beginner": $tmp = "Anfänger"; break;
     case "Advanced": $tmp = "Fortgeschrittener"; break;
     case "Expert": $tmp = "Experte"; break;

     case "Projects": $tmp = "Projekte"; break;
     case "Manage your Project List": $tmp = "Projektliste verwalten"; break;

     case "Search": $tmp = "Suche"; break;
     case "Language": $tmp = "Sprache"; break;
     case "Go": $tmp = "Los"; break;

     case "Done": $tmp = "Ausgeführt"; break;
     case "Your Profile has been succesfully changed": $tmp = "Ihre Profiledaten wurden erfolgreich geändert"; break;
     case "Your Project Data were included successfully": $tmp = "Ihre Projektdaten wurden erfolgreich eingetragen"; break;
     case "Please proceed with the main page": $tmp = "Bitte mit Hauptseite fortfahren"; break;

// Languages
	 case "English": $tmp = "Englisch"; break;
	 case "German": $tmp = "Deutsch"; break;
	 case "Spanish": $tmp = "Spanisch"; break;
	 case "French": $tmp = "Französisch"; break;

// FAQ
     case "Frequently Asked Questions": $tmp = "Oft gestellte Fragen"; break;
     case "Question": $tmp = "Frage"; break;
     case "Answer": $tmp = "Antwort"; break;

//Search
     case "DevCounter Search by Category": $tmp = "DevCounter Kategoriesuche"; break;
     case "Countries": $tmp = "L&auml;nder"; break;
     case "Spoken Languages": $tmp = "Gesprochene Sprachen"; break;
     case "Programming &amp; Computer Abilities": $tmp = "Programmier- &amp; Computerf&auml;higkeiten"; break;
     case "All in one": $tmp = "Alles auf einmal"; break;
     case "Search for Languages spoken": $tmp = "Suche nach gesprochen Sprachen"; break;
     case "Please select desired Language": $tmp = "Bitte gew&uuml;nschte Sprache ausw&auml;hlen"; break;
     case "Search for Projects": $tmp = "Suche nach Projekten"; break;
     case "Enter Name of <B>one</B> Project": $tmp = "Gib den Namen <B>eines</B> Projektes ein"; break;
     case "Results": $tmp = "Ergebnisse"; break;
     case "No Results": $tmp = "keine Ergebnisse"; break;
     case "Search Results": $tmp = "Suchergebisse"; break;
     case "Search for Countries": $tmp = "Suche nach L&auml;ndern"; break;
     case "Please select desired Country": $tmp = "Bitte das gew&uuml;nschte Land ausw&auml;hlen"; break;
     case "Search for All in one": $tmp = "Nach allem auf einmal suchen"; break;


// User registration
     case "Register as a new User": $tmp = "Registrierung als neuer Benutzer"; break;
     case "Username": $tmp = "Benutzername"; break;
     case "Password": $tmp = "Passwort"; break;
     case "Confirm Password": $tmp = "Passwort bestätigen"; break;
     case "Realname": $tmp = "Name"; break;
     case "Register": $tmp = "Registrieren"; break;
     case "Developer Registration": $tmp = "Entwicklerregistrierung"; break;
     case "Congratulations": $tmp = "Gratulation"; break;
     case "You have registered on $GLOBALS[sys_name]": $tmp = "Sie haben sich bei $GLOBALS[sys_name] registriert"; break;
     case "Your new username is": $tmp = "Ihr neuer Benutzername ist"; break;
     case "You are now being sent a confirmation email to verify your email address": $tmp = "Es wurde eine Bestätigung per E-Mail an Sie gesendet, um Ihre E-Mail-Adresse zu überprüfen"; break;
     case "Visiting the link sent to you in this email will activate your account": $tmp = "Wenn Sie die in dieser E-Mail gesendete Seite besuchen wird Ihre Benutzerkennung freigeschaltet"; break;
     case "Thank you for registering on the $GLOBALS[sys_name] Site. In order": $tmp = "Danke für Ihre Registrierung bei $GLOBALS[sys_name]. Um Ihre"; break;
     case "to complete your registration, visit the following URL": $tmp = "Registrierung abzuschließen, besuchen Sie die folgende URL"; break;
     case "Enjoy the site": $tmp = "Wir hoffen, dass Ihnen $GLOBALS[sys_name] gefällt"; break;
     case " -- the $GLOBALS[sys_name] crew": $tmp = " -- die $GLOBALS[sys_name] Crew"; break;
     case "Verification of Registration": $tmp = "Verifikation der Registrierung"; break;
     case "Your account is now activated. Please login": $tmp = "Ihre Benutzerkennung ist jetzt freigeschaltet. Bitte loggen Sie sich ein"; break;

// Contact Developer
     case "Send": $tmp = "Senden"; break;
     case "contact developer": $tmp = "an Entwickler schreiben"; break;
     case "write Developer": $tmp = "an Entwickler schreiben"; break;     
     case "Subject:": $tmp = "Betreff:"; break;
     case "Your EMail Address:": $tmp = "Deine EMail Adresse"; break;
     case "Content:": $tmp = "Inhalt:"; break;

// Forget password / Remind me
     case "Register as a new User": $tmp = "Registrierung als neuer Benutzer"; break;
     case "Remind me": $tmp = "Erinnern"; break;
     case "Your Username and Password for $GLOBALS[sys_name] is": $tmp = "Ihr Benutzername und Passwort für $GLOBALS[sys_name] ist"; break;
     case "Please keep this e-mail for further reference": $tmp = "Bitte bewahren Sie diese E-Mail zur späteren Referenzierung auf"; break;
     case "You will get your Password by e-mail in a couple of minutes": $tmp = "Sie erhalten Ihr Passwort per E-Mail in wenigen Minuten"; break;

// Change User Parameters
     case "Change Developer Parameters": $tmp = "Änderung der Entwicklerdaten"; break;
     case "Remind me": $tmp = "Erinnerung"; break;
     case "Modification": $tmp = "Modifiziert"; break;
     case "Creation": $tmp = "Erzeugt"; break;
     case "Permission": $tmp = "Rechte"; break;
     case "Change": $tmp = "Ändern"; break;
     case "Password and/or E-Mail Address of": $tmp = "Passwort und/oder E-Mail-Adresse von"; break;
     case "is changed": $tmp = "wurden geändert"; break;

// Login
     case "$GLOBALS[sys_name] Login": $tmp = "Bei $GLOBALS[sys_name] Einloggen"; break;
     case "Welcome to $GLOBALS[sys_name]": $tmp = "Willkommen bei $GLOBALS[sys_name]"; break;
     case "You are logged in as": $tmp = "Sie sind eingeloggt als"; break;
     case "with": $tmp = "mit"; break;
     case "permission": $tmp = "Rechten"; break;
     case "Your authentication is valid until": $tmp = "Ihre Authentifizierung ist gültig bis"; break;

// Logout
     case "You have been logged in as": $tmp = "Sie waren eingeloggt als"; break;
     case "Your authentication was valid until": $tmp = "Ihre Authentifizierung war gültig bis"; break;
     case "This is all over now. You have been logged out": $tmp = "Dies ist nun vorbei. Sie haben sich ausgeloggt"; break;

// User admin
     case "Action": $tmp = "Aktion"; break;
     case "Delete": $tmp = "Löschen"; break;
     case "Create User": $tmp = "Benutzer Erzeugen"; break;
     case "User Creation": $tmp = "Benutzer einrichten"; break;
     case "created": $tmp = "eingerichtet"; break;
     case "User Change": $tmp = "Benutzer Ändern"; break;
     case "User Deletion": $tmp = "Benutzer Löschen"; break;
     case "is deleted": $tmp = "wurden gelöscht"; break;

// Announcements
    case "by": $tmp = "von"; break;
    case "on": $tmp = "am"; break;
	case "hits": $tmp = "Zugriffe"; break;

// Statistics
	 case "$GLOBALS[sys_name] Statistics": $tmp = "$GLOBALS[sys_name] Statistiken"; break;
	 case "General $GLOBALS[sys_name] Statistics": $tmp = "Allgemeine $GLOBALS[sys_name] Statistiken"; break;

// General Statistics
	 case "Number of Applications in $GLOBALS[sys_name]": $tmp = "Anzahl der Anwendungen in $GLOBALS[sys_name]"; break;
	 case "Developers by Year of Birth": $tmp = "Entwickler nach Geburtsjahr"; break;
	 case "Developer by Visits": $tmp = "Entwicklern nach Besuchen"; break;
	 case "Developers by Profession": $tmp = "Entwickler nach Beruf"; break;
	 case "Developers by Gender": $tmp = "Entwickler nach Geschlecht"; break;
	 case "Developers by Qualification": $tmp = "Entwickler nach Abschluß"; break;
	 case "Developers by Email Domains": $tmp = "Entwickler nach Email-Domain"; break;
	 case "Developers by Programming Abilities": $tmp = "Entwickler nach Programmier-Erfahrung"; break;
	 case "Developers by Programming Languages/Tools": $tmp = "Entwickler nach Programmiersprachen/Werkzeug-Erfahrung"; break;
	 case "Developers by Nationality": $tmp = "Entwickler nach Herkunftsland"; break;
	 case "Developers by Countries currently live in": $tmp = "Entwickler nach Ländern, in denen man momentan lebt"; break;
	 case "Developers by Mother Tonque": $tmp = "Entwickler nach Muttersprache"; break;

	 case "Number of Developers in $GLOBALS[sys_name]": $tmp = "Anzahl der Entwickler in $GLOBALS[sys_name]"; break;
	 case "Number of today's visitors": $tmp = "Anzahl der heutigen Besucher"; break;
	 case "Number of Projects": $tmp = "Anzahl der Projekte"; break;
	 case "Number of Countries": $tmp = "Anzahl der Länder"; break;
	 case "Number of Languages": $tmp = "Anzahl der Sprachen"; break;
	 case "Number of Programming Abilities": $tmp = "Anzahl der Programmier-Erfahrung"; break;
	 case "Number of Programming Languages/Tools": $tmp = "Anzahl der Programmiersprachen/Werkzeug-Erfahrung"; break;
	 case "Number of Visits on Developers": $tmp = "Anzahl der Besucher von Entwicklern"; break;
     case "Number of Insertions and Modifications": $tmp = "Anzahl der Eintragungen und Modifikationen"; break;
     case "Today": $tmp = "Heute"; break;
     case "Last&nbsp;Week": $tmp = "Letzte&nbsp;Woche"; break;
	 case "$GLOBALS[sys_name] Version": $tmp = "$GLOBALS[sys_name] Version"; break;
     case "No.": $tmp = "Nr."; break;
     case "Developers listed by Year of Birth": $tmp = "Entwickler geordnet nach Geburtsjahr"; break;
     case "Developers listed by Number of Visits": $tmp = "Entwickler geordnet nach der Besucheranzahl"; break;
     case "Developers listed by Profession": $tmp = "Entwickler geordnet nach Beruf"; break;
     case "Developers listed by Gender": $tmp = "Entwickler geordnet nach Geschlecht"; break;
     case "Developers listed by Qualification": $tmp = "Entwickler geordnet nach Abschluß"; break;
     case "Developers listed by Email Domain": $tmp = "Entwickler geordnet nach Email-Domain"; break;
     case "Developers listed by Programming Abilities": $tmp = "Entwickler geordnet nach Programmier-Erfahrung"; break;
     case "Developers listed by Programming Languages/Tools": $tmp = "Entwickler geordnet nach Programmiersprachen/Werkzeug-Erfahrung"; break;
     case "Developers listed by Nationality": $tmp = "Entwickler geordnet nach Herkunftsland"; break;
     case "Developers listed by Countries currently live in": $tmp = "Entwickler geordnet nach Ländern, in denen man momentan lebt"; break;
     case "Developers listed by Mother Tongue": $tmp = "Entwickler geordnet nach Muttersprache"; break;


// Errors
     case "Access denied": $tmp = "Zugriff verweigert"; break;
     case "Error": $tmp = "Fehler"; break;
     case "does not exist": $tmp = "existiert nicht"; break;
     case "Change User Parameters failed": $tmp = "Änderung der Benutzerdaten ist fehlgeschlagen"; break;
     case "No Application ID specified": $tmp = "Keine Anwendungs-ID angegeben"; break;
     case "No Application Name specified": $tmp = "Kein Anwendungsname angegeben"; break;
     case "Please select": $tmp = "Bitte wählen Sie"; break;
     case "Parameter missing": $tmp = "Parameter fehlt"; break;
     case "and": $tmp = "und"; break;
     case "User": $tmp = "Benutzer"; break;
     case "already exists": $tmp = "existiert bereits"; break;
     case "Please select a different Username": $tmp = "Bitte wählen Sie einen anderen Benutzernamen"; break;
     case "Please enter": $tmp = "Bitte angeben:"; break;
     case "Either your Username or E-Mail Address is unknown": $tmp = "Entweder Ihr Benutzername oder E-Mail-Adresse ist unbekannt"; break;
     case "Please try again": $tmp = "Bitte versuchen Sie es nochmal"; break;
     case "If you are not yet a registered User, please select": $tmp = "Wenn Sie noch kein registrierter Benutzer sind, wählen Sie bitte"; break;
     case "Verification of Registration failed": $tmp = "Verifikation der Registrierung ist fehlgeschlagen"; break;
     case "User Change failed": $tmp = "Benutzer ändern ist fehlgeschlagen"; break;
     case "Registration of new User failed": $tmp = "Registrierung des neuen Benutzers ist fehlgeschlagen"; break;
     case "Database Access failed": $tmp = "Datenbankzugriff ist fehlgeschlagen"; break;
     case "User Deletion failed": $tmp = "Benutzer Löschen ist fehlgeschlagen"; break;
     case "No more Apps for this day": $tmp = "Keine weiteren Anwendungen für diesen Tag"; break;
     case "Either your Username or Password are invalid": $tmp = "Entweder Ihr Benutzername oder Passwort ist falsch"; break;
     case "The passwords are not identical": $tmp = "Die Passworte sind nicht identisch"; break;
     case "Please try again": $tmp = "Bitte versuchen Sie es nochmal"; break;
     case "License description is not available": $tmp = "Lizenzbeschreibung ist nicht verfügbar"; break;
     case "No Frequently Asked Questions exist": $tmp = "Es existieren keine oft gestellten Fragen"; break;
     case "Developer did not specify a Profile yet": $tmp = "Entwickler hat bis jetzt noch keine Profildaten spezifiziert"; break;
     case "Developer does not allow to contact him": $tmp = "Entwickler erlaubt keinen Kontakt"; break;
     case "Unknown Developer": $tmp = "Entwickler unbekannt"; break;
     case "No Developer found": $tmp = "Kein Entwickler gefunden"; break;
     case "Invalid action specified": $tmp = "Unzulässige Aktion angegeben"; break;

// adm_langs_tools.php
    case "Success": $tmp = "Erfolg"; break;
    case "ProgLanguage": $tmp = "Programmiersprache"; break;
    case "ColumnName": $tmp = "Spaltenname"; break;
    case "Programming Abilities" : $tmp = "Programmierfertigkeiten"; break;
    case "ProgAbilityName" : $tmp = "ProgFertigkeitenName"; break;
    case "Programming Languages": $tmp = "Programmiersprachen"; break;
    case "ProgLanguageName": $tmp = "ProgSprachenName"; break;
    case "ProgLanguage updated": $tmp = "ProgSprache ge&auml;ndert"; break;
    case "ProgLanguage added": $tmp = "ProgSprache hinzugef&uuml;gt"; break;
    case "ProgLanguage removed": $tmp = "ProgSprache entfernt"; break;
    case "Ability updated": $tmp = "F&auml;higkeit ge&auml;ndert"; break;
    case "Ability added": $tmp = "F&auml;higkeit hinzugef&uuml;gt"; break;
    case "Add Ability": $tmp = "F&auml;higkeit hinzuf&uuml;gen"; break;
    case "Add ProgLanguage": $tmp = "ProgSprache hinzuf&uuml;gen"; break;
    case "Ability removed": $tmp = "F&auml;higkeit entfernt"; break;

// admuser.php
    case "User Administration": $tmp = "Benutzeradministration"; break;
    case "There can only be one anonymous user in the system": $tmp = "Es darf nur ein anonymer Benutzer existieren"; break;
    case "The anonymous permission is incompatible with another type of permission": $tmp = "Das anonyme Recht ist inkompatibel zu anderen Rechten"; break;


// showprofile.php

    case "Currently lives in": $tmp = "lebt momentan in"; break;
    case "Languages spoken": $tmp = "gesprochene Sprachen"; break;
    case "Number of Free Software/Open Source Projects": $tmp = "Anzahl der Free Software/Open Source Projekte"; break;
    case "Developer last modified": $tmp = "Entwickler zuletzt geändert"; break;
    case "Developer created": $tmp = "Entwickler erstellt"; break;
    case "Profile last modified": $tmp = "Profildaten zuletzt geändert"; break;
    case "# of Visits": $tmp = "# der Besuche"; break;
    case "Registration Number": $tmp = "Registrierungsnummer"; break;
    case "Programming Experience": $tmp = "Programmier-Erfahrung"; break;
    case "Languages/Tools Experience": $tmp = "Programmiersprachen/Werkzeug-Erfahrung"; break;
    case "Thank you": $tmp = "Danksagung"; break;
    case "Thank you for entering your Profile": $tmp = "Danke für die Eingabe Ihrer Profildaten"; break;
    case "Please proceed with the main page ": $tmp = "Bitte mit der Hauptseite fortfahren"; break;

// admfaq.php and insfaq.php

    case "Enter a New Frequently Asked Question": $tmp = "Erstellen einer neuen häufig gestellten Frage"; break;
    case "Frequently Asked Questions Administration": $tmp = "Administration der häufig gestellten Fragen"; break;
    case "Delete this faq? (please, think there's no way for undoing comment deletion)": $tmp = "Diese Frage löschen? (Bitte bedenken Sie, dass es keine Möglichkeit gibt, dies wieder rückgängig zu machen)"; break;
    case "Create": $tmp = "Erstelle"; break;
    case "FAQ Deleted": $tmp = "Frage gelöscht"; break;
    case "FAQ Administration": $tmp = "Administration der häufig gestellten Fragen"; break;
    case "The following FAQ has been modified": $tmp = "Die folgende Frage wurde geändert"; break;
    case "The following FAQ has been inserted in this language": $tmp = "Die folgende Frage wurde erstellt in der Sprache"; break;

// admdate.php
    case "Modification date": $tmp = "Änderungsdatum"; break;
    case "History date": $tmp = "Datum der Historie"; break;

// footer.inc
    case "System Credits": $tmp = "Systembeschreibung"; break;

// login.php
    case "Anonymous login": $tmp = "Anonymes Login"; break;
    case "If you are not registered and/or you do not want to, you can login as an anonymous user by entering": $tmp = "Wenn Sie nicht registriert sind und/oder Sie möchten dies auch nicht, dann authentifizieren Sie sich als anonymer Benutzer durch Eingabe von"; break;
    case "as user name and": $tmp = "als Benutzername und"; break;
    case "as password.": $tmp = "als Passwort"; break;

// configure.php
    case "Enter your projects here": $tmp = "Projekte hier eingeben"; break;
    case "Project updated": $tmp = "Projekt ge&auml;ndert"; break;
    case "Project deleted": $tmp = "Projekt gel&ouml;scht"; break;
    case "Project added": $tmp = "Projekt hinzugef&uuml;gt"; break;
    case "The Projects": $tmp = "Die Projekte"; break;
    case "Please proceed with the projects page": $tmp = "Bitte mit Projekt-Seite fortfahren"; break;
    
// Developers watch
    case "Set your Developers Watch": $tmp = "Setze Entwicklerausschau"; break;
    case "Which programming experiences you like to watch?": $tmp = "Welche Programmierfähigkeiten sollen beobachtet werden?"; break;
    case "Which languages/tools you like to watch?": $tmp = "Welche Programmiersprachen/Werkzeuge sollen beobachtet werden?"; break;
    case "Your Developers Watch has been set succesfully": $tmp = "Ihre Entwicklerausschau wurde eingerichtet"; break;
    case "Your Developers Watch has been deleted succesfully": $tmp = "Ihre Entwicklerausschau wurde gelöscht"; break;
    case "The following Developers match with the Watch of": $tmp = "Die folgenden Entwickler passen zur Entwicklerausschau von"; break;
    case "Developers Watch Notification was sent to": $tmp = "Ausschaumitteilung wurde gesendet an"; break;
    case "Send Watch Notifications": $tmp = "Sende Ausschaumitteilungen"; break;
    case "You will be informed by email, if developers with corresponding abilities and expriences becomes available": $tmp = "Sie werden per eMail benachrichtigt, wenn Entwickler mit entsprechenden Kenntnissen und Erfahrungen verfügbar sind"; break;

// If no translation available, keep the original phrase
      
     default: $tmp = "$phrase"; break;
}
?>
